### ISSUE TITLE
No locale has been set and current locale is undefined.

### ISSUE THREAD

**Issue by jean-francine** [Locastic/ApiPlatformTranslationBundle#18] opened 2020-01-22 11:56 UTC
Hello,

I’m trying to use LocasticApiTranslationBundle with doctrine but I’m unable to make it work.

it tells me that there is no locale defined but I don't know where to declare the locale ?

Can you help me and tell me what I’m doing wrong please ?

In attachment, the stacktrace, 

the source entity (ReferenceMateriel) and the translation entity (ReferenceMaterielTranslation) I use.

Thank you in advance for your help.

Best regards

[ReferenceMateriel.txt](https://github.com/Locastic/ApiPlatformTranslationBundle/files/4097024/ReferenceMateriel.txt)
[ReferenceMaterielTranslation.txt](https://github.com/Locastic/ApiPlatformTranslationBundle/files/4097026/ReferenceMaterielTranslation.txt)
[stacktrace.txt](https://github.com/Locastic/ApiPlatformTranslationBundle/files/4097038/stacktrace.txt)

**Comment by jean-francine** [comment] 2020-01-23 08:43
I used ApiPlatformTranslationBundle with symfony 4.3

**Comment by paullla** [comment] 2020-01-27 12:10
Hi @jean-francine I think the problem is in ReferenceMateriel constructor. You didn't call parent constructor call, so locale isn't set at all. This is what is should look like:
`    public function __construct() {
        parent::__construct();
        $this->translations = new ArrayCollection();
    }`
Please let me know if this helps.

**Comment by jean-francine** [comment] 2020-01-29 09:02
Thanks you for the quick reply !
Unfortunately that does not solve the problem.
I have the following lines which are the defaults setting in the file config/packages/translation.yaml :

framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en

is this the correct setting ?

**Comment by paullla** [comment] 2020-02-18 10:42
@jean-francine can you check if this fixed your problem: https://github.com/Locastic/ApiPlatformTranslationBundle/pull/19

**Comment by jean-francine** [comment] 2020-02-18 11:23
Hi @paullla ! I just updated the bundle and it works like a charm !
Thank you so much !!

**Comment by paullla** [comment] 2020-02-18 11:24
Thank you for your feedback :) Closing the issue.

**Closed by paullla** 2020-02-18 11:24 UTC
